# Generated by Django 4.1.7 on 2023-03-22 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField(max_length=255)),
                ('tag', models.TextField(max_length=255)),
                ('balance', models.FloatField()),
                ('name', models.TextField(max_length=255)),
                ('surname', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.TextField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('dest_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='mtaa_test.account')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('create_time', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mtaa_test.account')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
                ('send_time', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mtaa_test.account')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mtaa_test.room')),
            ],
        ),
        migrations.CreateModel(
            name='DebtsClaims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('debt_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dc_account1', to='mtaa_test.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='claims',
            field=models.ManyToManyField(to='mtaa_test.debtsclaims'),
        ),
        migrations.AddField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(to='mtaa_test.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='transactions',
            field=models.ManyToManyField(to='mtaa_test.transaction'),
        ),
    ]
